### ISSUE TITLE
Wrap other parameter from tekla

### ISSUE THREAD

**Issue by Raimond1233** [efdiloreto/PyTekla#1]
Hello Eduardo, I'm very interested in your project. But I don't know how to "wrap" other parameters from Tekla, such as: part_prefix, part_startnumber, assembly_prefix... Could you help with ? Thank you in advance :)

**Comment by efdiloreto** [comment]
Sure! Let me create an example

**Comment by Raimond1233** [comment]
Super thanks Eduardo :)

**Comment by efdiloreto** [comment]
@Raimond1233 My Tekla license is expired, so I cannot try the code in an actual model.

For setting the part number to a part I would do this, referring to this [API](https://developer.tekla.com/tekla-structures/api/28/14512)

```
numbering_series = wrap("Model.NumberingSeries")
numbering_series.prefix = "P"
numbering_series.start_number = 1

part.part_number = numbering_series

model.commit_changes("Some Changes")
```

Let me know if this works for you.

**Comment by Raimond1233** [comment]
Super. Thanks a lot Eduardo :)
