### ISSUE TITLE
Problem importing module

### ISSUE THREAD

**Issue by UshakovVyacheslav** [efdiloreto/PyTekla#4]
Hi, Eduardo.
After I installed your module I tried to connect to the model, but I got an error: No module named 'Tekla'.

my code:

import pytekla
from Tekla.Structures.Model import Model, Beam

then
![image](https://github.com/efdiloreto/PyTekla/assets/117026798/24233d84-975b-4792-8a79-d104834c175d)

but when setting the path there is no problem
![image](https://github.com/efdiloreto/PyTekla/assets/117026798/d51aaab5-f29e-4b04-bada-46d4f9cb1539)

what could be the problem?

**Comment by efdiloreto** [comment]
I think the problem could be that you are using Tekla 2019. And the API is changing between versions. PyTekla was created for Tekla 2022 and planing to update for future releases.

**Comment by UshakovVyacheslav** [comment]
Thanks Eduardo, new versions have connectivity. But is it possible to somehow add older versions TS?

**Comment by efdiloreto** [comment]
@UshakovVyacheslav Not using PyTekla. But you can still access using Python.NET like I did with PyTekla.
